[2024-10-17T23:36:02.908+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-17T23:36:02.919+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_SCRIPT.EMAIL_FAILURE manual__2024-10-17T23:34:24.200224+00:00 [queued]>
[2024-10-17T23:36:02.925+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_SCRIPT.EMAIL_FAILURE manual__2024-10-17T23:34:24.200224+00:00 [queued]>
[2024-10-17T23:36:02.925+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-17T23:36:02.935+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): EMAIL_FAILURE> on 2024-10-17 23:34:24.200224+00:00
[2024-10-17T23:36:02.939+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-17T23:36:02.940+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2024-10-17T23:36:02.940+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_SCRIPT', 'EMAIL_FAILURE', 'manual__2024-10-17T23:34:24.200224+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_file.py', '--cfg-path', '/tmp/tmpij676tyg']
[2024-10-17T23:36:02.941+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask EMAIL_FAILURE
[2024-10-17T23:36:02.969+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_SCRIPT.EMAIL_FAILURE manual__2024-10-17T23:34:24.200224+00:00 [running]> on host c5976fb17317
[2024-10-17T23:36:03.023+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='guilhermeavila.orlando@gmail.com' AIRFLOW_CTX_DAG_OWNER='Guilherme Orlando' AIRFLOW_CTX_DAG_ID='ETL_SCRIPT' AIRFLOW_CTX_TASK_ID='EMAIL_FAILURE' AIRFLOW_CTX_EXECUTION_DATE='2024-10-17T23:34:24.200224+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-17T23:34:24.200224+00:00'
[2024-10-17T23:36:03.023+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-17T23:36:06.246+0000] {logging_mixin.py:190} INFO - E-mail enviado com sucesso!
[2024-10-17T23:36:06.246+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-17T23:36:06.255+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-17T23:36:06.256+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ETL_SCRIPT, task_id=EMAIL_FAILURE, run_id=manual__2024-10-17T23:34:24.200224+00:00, execution_date=20241017T233424, start_date=20241017T233602, end_date=20241017T233606
[2024-10-17T23:36:06.282+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-17T23:36:06.293+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-17T23:36:06.294+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
